import numpy as np
print("JOYAL JOSE\n21MCA026")
array=np.random.randint( 10,size=(2,2))
print("Matrix\n------")
print(array)
print ("\nInverse of the matrics is")
print(np.linalg.inv(array))
det = np.linalg.det(array)
print("\nDeterminant of given matrix : ",det)
res = array.flatten()
print("\nConvert into 1 d array : ",res)
w, v = np.linalg.eig(array)
print ("\nEgien values : ",w)
print("\nEgien vectors : \n",v)
