import numpy as np
print("JOYAL JOSE\n21MCA026")
array1=np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])
array2=np.array([[4, 5, 6], [3, 4, 5], [7, 8, 2]])
print(" Matrix - 1\n------------")
print(array1)
print(" Matrix - 2\n------------\n")
print(array2)
print("\n Matrix - 1 + Matrix -2\n-----------------------")
print(np.add(array1, array2))
print("\n Matrix - 1 - Matrix -2\n-----------------------")
print(np.subtract(array1, array2))
print("\n Matrix - 1 * Matrix -2\n-----------------------")
print(np.multiply(array1,array2))
print("\n Matrix - 1 / Matrix -2\n-----------------------")
print(np.divide(array1,array2))
print("\n Transpose of Matrix - 1\n-----------------------")
print(array1.T)
print("\nSum of the diagonal elements",sum(np.diag(array1)))